"""Create initial tables with ML columns

Revision ID: fd4c7e364796
Revises: 
Create Date: 2026-06-27 16:29:46.333913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4c7e364796'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_crawled', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_url'), 'sites', ['url'], unique=True)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('token_text', sa.Text(), nullable=True),
    sa.Column('tf_idf', sa.ARRAY(sa.REAL()), nullable=True),
    sa.Column('relevantnost', sa.Float(), nullable=True),
    sa.Column('crawled_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_index(op.f('ix_pages_site_id'), 'pages', ['site_id'], unique=False)
    op.create_index('ix_pages_site_url', 'pages', ['site_id', 'url'], unique=True)
    op.create_index(op.f('ix_pages_url'), 'pages', ['url'], unique=False)
    op.create_table('inverted_index',
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word', 'page_id')
    )
    op.create_index('ix_inverted_index_page_id', 'inverted_index', ['page_id'], unique=False)
    op.create_index('ix_inverted_index_word', 'inverted_index', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inverted_index_word', table_name='inverted_index')
    op.drop_index('ix_inverted_index_page_id', table_name='inverted_index')
    op.drop_table('inverted_index')
    op.drop_index(op.f('ix_pages_url'), table_name='pages')
    op.drop_index('ix_pages_site_url', table_name='pages')
    op.drop_index(op.f('ix_pages_site_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_sites_url'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
